[package]
name = "sharknado"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.9.1"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
tokio = { version = "1.47.1", features = ["full"] }
